# Generated by Django 6.0.5 on 2026-06-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopy.catagory', verbose_name='التصنيف')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
