# Generated by Django 6.0.5 on 2026-06-15 11:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0002_catagory_info_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='المحتوى'),
        ),
    ]
