# Generated by Django 6.0.5 on 2026-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0003_rename_name_catagory_name_alter_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
