# Generated by Django 6.0.5 on 2026-06-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0004_info_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
